import _ from 'lodash'

export default {
  /**
   * Push a POI to the list.
   *
   * A POI should have a unique Id, it wont be pushed without it.
   *
   * @param state
   * @param {Object} item - the now POI to add to the collection
   * @param {String} item._id - generated id (generated by the add action
   * @param {String} item._id - the name of the POI
   * @param {{x: Number, y: Number}} item.pos - the relative position on the map
   */
  ADD_A_POI: (state, item) => {
    if (!item._id) return
    if (_.findIndex(state.list, i => i._id === item._id) === -1) {
      state.list.push(item)
    }
  },

  /**
   * remove a poi from the list
   *
   * @param state
   * @param {String|{_id:String}} item - stored _id as an Object or String
   */
  REMOVE_A_POI: (state, item) => {
    // can be undefined !
    let _id = _.isObject(item)
      ? item._id
      : item

    _.remove(state.list, i => i._id === _id)
  }
}
